version: '2'

services:
  web:
    build:
      context: .
      dockerfile: .docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html:cached
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - .:/var/www/html:cached
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/zzz-php.ini
    environment:
      - XDEBUG_CONFIG=idekey=PHPSTORM remote_host=docker.for.mac.localhost
      - PHP_IDE_CONFIG=serverName=localhost
    links:
      - db
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "13306:3306"
  maildev:
    image: djfarrelly/maildev
    ports:
      - "11080:80"
  node:
    build:
      context: .docker
      dockerfile: node/Dockerfile
    volumes:
      - .:/app:cached
    tty: true
    ports:
      - 3000:3000
      - 35729:35729
volumes:
  db-data: