version: '2'

services:
  php:
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
    volumes:
      - .:/var/www/html:cached
      - .docker/php/php.ini:/usr/local/etc/php/conf.d/zzz-php.ini
    environment:
      - XDEBUG_CONFIG=idekey=PHPSTORM remote_host=docker.for.mac.localhost
      - PHP_IDE_CONFIG=serverName=localhost